version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: hp_nginx
    depends_on:
      - php
    ports:
      - "8081:80"
    volumes:
      - ../hapoLearn:/var/www/html
      - ./.deployment/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - hapo-network
  php:
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../hapoLearn:/var/www/html
    container_name: hp_app
    ports:
      - "9000:9000"
    networks:
      - hapo-network
networks:
  hapo-network:
    external: true